# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: srv6pmCommons.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='srv6pmCommons.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x13srv6pmCommons.proto\"Y\n\x0c\x43olorOptions\x12\x19\n\x11interval_duration\x18\x01 \x01(\r\x12\x14\n\x0c\x64\x65lay_margin\x18\x02 \x01(\r\x12\x18\n\x10numbers_of_color\x18\x03 \x01(\r\"\'\n\x15StopExperimentRequest\x12\x0e\n\x06sdlist\x18\x01 \x01(\t\".\n\x1cRetriveExperimentDataRequest\x12\x0e\n\x06sdlist\x18\x01 \x01(\t\"5\n\x16\x45xperimentDataResponse\x12\x1b\n\x06status\x18\x01 \x01(\x0e\x32\x0b.StatusCode\"2\n\x13StopExperimentReply\x12\x1b\n\x06status\x18\x01 \x01(\x0e\x32\x0b.StatusCode**\n\x12MesurementProtocol\x12\t\n\x05STAMP\x10\x00\x12\t\n\x05TWAMP\x10\x01*w\n\nStatusCode\x12\x12\n\x0eSTATUS_SUCCESS\x10\x00\x12\"\n\x1eSTATUS_OPERATION_NOT_SUPPORTED\x10\x01\x12\x16\n\x12STATUS_BAD_REQUEST\x10\x02\x12\x19\n\x15STATUS_INTERNAL_ERROR\x10\x03\x62\x06proto3'
)

_MESUREMENTPROTOCOL = _descriptor.EnumDescriptor(
  name='MesurementProtocol',
  full_name='MesurementProtocol',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STAMP', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TWAMP', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=310,
  serialized_end=352,
)
_sym_db.RegisterEnumDescriptor(_MESUREMENTPROTOCOL)

MesurementProtocol = enum_type_wrapper.EnumTypeWrapper(_MESUREMENTPROTOCOL)
_STATUSCODE = _descriptor.EnumDescriptor(
  name='StatusCode',
  full_name='StatusCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STATUS_SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_OPERATION_NOT_SUPPORTED', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_BAD_REQUEST', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_INTERNAL_ERROR', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=354,
  serialized_end=473,
)
_sym_db.RegisterEnumDescriptor(_STATUSCODE)

StatusCode = enum_type_wrapper.EnumTypeWrapper(_STATUSCODE)
STAMP = 0
TWAMP = 1
STATUS_SUCCESS = 0
STATUS_OPERATION_NOT_SUPPORTED = 1
STATUS_BAD_REQUEST = 2
STATUS_INTERNAL_ERROR = 3



_COLOROPTIONS = _descriptor.Descriptor(
  name='ColorOptions',
  full_name='ColorOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='interval_duration', full_name='ColorOptions.interval_duration', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='delay_margin', full_name='ColorOptions.delay_margin', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='numbers_of_color', full_name='ColorOptions.numbers_of_color', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=112,
)


_STOPEXPERIMENTREQUEST = _descriptor.Descriptor(
  name='StopExperimentRequest',
  full_name='StopExperimentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sdlist', full_name='StopExperimentRequest.sdlist', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=153,
)


_RETRIVEEXPERIMENTDATAREQUEST = _descriptor.Descriptor(
  name='RetriveExperimentDataRequest',
  full_name='RetriveExperimentDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sdlist', full_name='RetriveExperimentDataRequest.sdlist', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=201,
)


_EXPERIMENTDATARESPONSE = _descriptor.Descriptor(
  name='ExperimentDataResponse',
  full_name='ExperimentDataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ExperimentDataResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=203,
  serialized_end=256,
)


_STOPEXPERIMENTREPLY = _descriptor.Descriptor(
  name='StopExperimentReply',
  full_name='StopExperimentReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='StopExperimentReply.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=258,
  serialized_end=308,
)

_EXPERIMENTDATARESPONSE.fields_by_name['status'].enum_type = _STATUSCODE
_STOPEXPERIMENTREPLY.fields_by_name['status'].enum_type = _STATUSCODE
DESCRIPTOR.message_types_by_name['ColorOptions'] = _COLOROPTIONS
DESCRIPTOR.message_types_by_name['StopExperimentRequest'] = _STOPEXPERIMENTREQUEST
DESCRIPTOR.message_types_by_name['RetriveExperimentDataRequest'] = _RETRIVEEXPERIMENTDATAREQUEST
DESCRIPTOR.message_types_by_name['ExperimentDataResponse'] = _EXPERIMENTDATARESPONSE
DESCRIPTOR.message_types_by_name['StopExperimentReply'] = _STOPEXPERIMENTREPLY
DESCRIPTOR.enum_types_by_name['MesurementProtocol'] = _MESUREMENTPROTOCOL
DESCRIPTOR.enum_types_by_name['StatusCode'] = _STATUSCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ColorOptions = _reflection.GeneratedProtocolMessageType('ColorOptions', (_message.Message,), {
  'DESCRIPTOR' : _COLOROPTIONS,
  '__module__' : 'srv6pmCommons_pb2'
  # @@protoc_insertion_point(class_scope:ColorOptions)
  })
_sym_db.RegisterMessage(ColorOptions)

StopExperimentRequest = _reflection.GeneratedProtocolMessageType('StopExperimentRequest', (_message.Message,), {
  'DESCRIPTOR' : _STOPEXPERIMENTREQUEST,
  '__module__' : 'srv6pmCommons_pb2'
  # @@protoc_insertion_point(class_scope:StopExperimentRequest)
  })
_sym_db.RegisterMessage(StopExperimentRequest)

RetriveExperimentDataRequest = _reflection.GeneratedProtocolMessageType('RetriveExperimentDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _RETRIVEEXPERIMENTDATAREQUEST,
  '__module__' : 'srv6pmCommons_pb2'
  # @@protoc_insertion_point(class_scope:RetriveExperimentDataRequest)
  })
_sym_db.RegisterMessage(RetriveExperimentDataRequest)

ExperimentDataResponse = _reflection.GeneratedProtocolMessageType('ExperimentDataResponse', (_message.Message,), {
  'DESCRIPTOR' : _EXPERIMENTDATARESPONSE,
  '__module__' : 'srv6pmCommons_pb2'
  # @@protoc_insertion_point(class_scope:ExperimentDataResponse)
  })
_sym_db.RegisterMessage(ExperimentDataResponse)

StopExperimentReply = _reflection.GeneratedProtocolMessageType('StopExperimentReply', (_message.Message,), {
  'DESCRIPTOR' : _STOPEXPERIMENTREPLY,
  '__module__' : 'srv6pmCommons_pb2'
  # @@protoc_insertion_point(class_scope:StopExperimentReply)
  })
_sym_db.RegisterMessage(StopExperimentReply)


# @@protoc_insertion_point(module_scope)
