# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import srv6pmCommons_pb2 as srv6pmCommons__pb2


class CreationTunnelStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateSRv6Tunnel = channel.unary_unary(
        '/CreationTunnel/CreateSRv6Tunnel',
        request_serializer=srv6pmCommons__pb2.SRv6EPRequest.SerializeToString,
        response_deserializer=srv6pmCommons__pb2.SRv6EPReply.FromString,
        )


class CreationTunnelServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateSRv6Tunnel(self, request, context):
    """Tunnel
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CreationTunnelServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateSRv6Tunnel': grpc.unary_unary_rpc_method_handler(
          servicer.CreateSRv6Tunnel,
          request_deserializer=srv6pmCommons__pb2.SRv6EPRequest.FromString,
          response_serializer=srv6pmCommons__pb2.SRv6EPReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'CreationTunnel', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
