# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: srv6pmSender.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import srv6pmCommons_pb2 as srv6pmCommons__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='srv6pmSender.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x12srv6pmSender.proto\x1a\x13srv6pmCommons.proto\"|\n\x1cStartExperimentSenderRequest\x12\x0e\n\x06sdlist\x18\x01 \x01(\t\x12&\n\x0esender_options\x18\x02 \x01(\x0b\x32\x0e.SenderOptions\x12$\n\rcolor_options\x18\x03 \x01(\x0b\x32\r.ColorOptions\"9\n\x1aStartExperimentSenderReply\x12\x1b\n\x06status\x18\x01 \x01(\x0e\x32\x0b.StatusCode\"W\n\rSenderOptions\x12\x30\n\x13mesurement_protocol\x18\x01 \x01(\x0e\x32\x13.MesurementProtocol\x12\x14\n\x0c\x64st_udp_port\x18\x02 \x01(\r2\xfe\x01\n\x13SRv6PMSenderService\x12O\n\x0fstartExperiment\x12\x1d.StartExperimentSenderRequest\x1a\x1b.StartExperimentSenderReply\"\x00\x12@\n\x0estopExperiment\x12\x16.StopExperimentRequest\x1a\x14.StopExperimentReply\"\x00\x12T\n\x18retriveExperimentResults\x12\x1d.RetriveExperimentDataRequest\x1a\x17.ExperimentDataResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[srv6pmCommons__pb2.DESCRIPTOR,])




_STARTEXPERIMENTSENDERREQUEST = _descriptor.Descriptor(
  name='StartExperimentSenderRequest',
  full_name='StartExperimentSenderRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sdlist', full_name='StartExperimentSenderRequest.sdlist', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sender_options', full_name='StartExperimentSenderRequest.sender_options', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='color_options', full_name='StartExperimentSenderRequest.color_options', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=167,
)


_STARTEXPERIMENTSENDERREPLY = _descriptor.Descriptor(
  name='StartExperimentSenderReply',
  full_name='StartExperimentSenderReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='StartExperimentSenderReply.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=226,
)


_SENDEROPTIONS = _descriptor.Descriptor(
  name='SenderOptions',
  full_name='SenderOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mesurement_protocol', full_name='SenderOptions.mesurement_protocol', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dst_udp_port', full_name='SenderOptions.dst_udp_port', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=228,
  serialized_end=315,
)

_STARTEXPERIMENTSENDERREQUEST.fields_by_name['sender_options'].message_type = _SENDEROPTIONS
_STARTEXPERIMENTSENDERREQUEST.fields_by_name['color_options'].message_type = srv6pmCommons__pb2._COLOROPTIONS
_STARTEXPERIMENTSENDERREPLY.fields_by_name['status'].enum_type = srv6pmCommons__pb2._STATUSCODE
_SENDEROPTIONS.fields_by_name['mesurement_protocol'].enum_type = srv6pmCommons__pb2._MESUREMENTPROTOCOL
DESCRIPTOR.message_types_by_name['StartExperimentSenderRequest'] = _STARTEXPERIMENTSENDERREQUEST
DESCRIPTOR.message_types_by_name['StartExperimentSenderReply'] = _STARTEXPERIMENTSENDERREPLY
DESCRIPTOR.message_types_by_name['SenderOptions'] = _SENDEROPTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StartExperimentSenderRequest = _reflection.GeneratedProtocolMessageType('StartExperimentSenderRequest', (_message.Message,), {
  'DESCRIPTOR' : _STARTEXPERIMENTSENDERREQUEST,
  '__module__' : 'srv6pmSender_pb2'
  # @@protoc_insertion_point(class_scope:StartExperimentSenderRequest)
  })
_sym_db.RegisterMessage(StartExperimentSenderRequest)

StartExperimentSenderReply = _reflection.GeneratedProtocolMessageType('StartExperimentSenderReply', (_message.Message,), {
  'DESCRIPTOR' : _STARTEXPERIMENTSENDERREPLY,
  '__module__' : 'srv6pmSender_pb2'
  # @@protoc_insertion_point(class_scope:StartExperimentSenderReply)
  })
_sym_db.RegisterMessage(StartExperimentSenderReply)

SenderOptions = _reflection.GeneratedProtocolMessageType('SenderOptions', (_message.Message,), {
  'DESCRIPTOR' : _SENDEROPTIONS,
  '__module__' : 'srv6pmSender_pb2'
  # @@protoc_insertion_point(class_scope:SenderOptions)
  })
_sym_db.RegisterMessage(SenderOptions)



_SRV6PMSENDERSERVICE = _descriptor.ServiceDescriptor(
  name='SRv6PMSenderService',
  full_name='SRv6PMSenderService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=318,
  serialized_end=572,
  methods=[
  _descriptor.MethodDescriptor(
    name='startExperiment',
    full_name='SRv6PMSenderService.startExperiment',
    index=0,
    containing_service=None,
    input_type=_STARTEXPERIMENTSENDERREQUEST,
    output_type=_STARTEXPERIMENTSENDERREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='stopExperiment',
    full_name='SRv6PMSenderService.stopExperiment',
    index=1,
    containing_service=None,
    input_type=srv6pmCommons__pb2._STOPEXPERIMENTREQUEST,
    output_type=srv6pmCommons__pb2._STOPEXPERIMENTREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='retriveExperimentResults',
    full_name='SRv6PMSenderService.retriveExperimentResults',
    index=2,
    containing_service=None,
    input_type=srv6pmCommons__pb2._RETRIVEEXPERIMENTDATAREQUEST,
    output_type=srv6pmCommons__pb2._EXPERIMENTDATARESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SRV6PMSENDERSERVICE)

DESCRIPTOR.services_by_name['SRv6PMSenderService'] = _SRV6PMSENDERSERVICE

# @@protoc_insertion_point(module_scope)
