# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import srv6pmCommons_pb2 as srv6pmCommons__pb2
import srv6pmReflector_pb2 as srv6pmReflector__pb2


class SRv6PMReflectorServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.startExperiment = channel.unary_unary(
        '/SRv6PMReflectorService/startExperiment',
        request_serializer=srv6pmReflector__pb2.StartExperimentReflectorRequest.SerializeToString,
        response_deserializer=srv6pmReflector__pb2.StartExperimentReflectorReply.FromString,
        )
    self.stopExperiment = channel.unary_unary(
        '/SRv6PMReflectorService/stopExperiment',
        request_serializer=srv6pmCommons__pb2.StopExperimentRequest.SerializeToString,
        response_deserializer=srv6pmCommons__pb2.StopExperimentReply.FromString,
        )
    self.retriveExperimentResults = channel.unary_unary(
        '/SRv6PMReflectorService/retriveExperimentResults',
        request_serializer=srv6pmCommons__pb2.RetriveExperimentDataRequest.SerializeToString,
        response_deserializer=srv6pmCommons__pb2.ExperimentDataResponse.FromString,
        )


class SRv6PMReflectorServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def startExperiment(self, request, context):
    """start an experiment
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def stopExperiment(self, request, context):
    """stop am experiment
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def retriveExperimentResults(self, request, context):
    """retrive data of an experiment
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SRv6PMReflectorServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'startExperiment': grpc.unary_unary_rpc_method_handler(
          servicer.startExperiment,
          request_deserializer=srv6pmReflector__pb2.StartExperimentReflectorRequest.FromString,
          response_serializer=srv6pmReflector__pb2.StartExperimentReflectorReply.SerializeToString,
      ),
      'stopExperiment': grpc.unary_unary_rpc_method_handler(
          servicer.stopExperiment,
          request_deserializer=srv6pmCommons__pb2.StopExperimentRequest.FromString,
          response_serializer=srv6pmCommons__pb2.StopExperimentReply.SerializeToString,
      ),
      'retriveExperimentResults': grpc.unary_unary_rpc_method_handler(
          servicer.retriveExperimentResults,
          request_deserializer=srv6pmCommons__pb2.RetriveExperimentDataRequest.FromString,
          response_serializer=srv6pmCommons__pb2.ExperimentDataResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'SRv6PMReflectorService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
